#cloud-config
package_upgrade: true
packages:
write_files:
  - owner: azureuser:azureuser
    path: /home/azureuser/myapp/job.sh
    content: |
      i=0
      while [ $i -lt 12 ]; do # 12 five-second intervals in 1 minute
        curl https://catfact.ninja/fact | json_pp >> /home/azureuser/myapp/cat.txt
        curl http://192.168.43.4 >> /home/azureuser/myapp/backend.txt
        sleep 5
        i=$(( i + 1 ))
      done
  - owner: azureuser:azureuser
    path: /home/azureuser/myapp/cleanup.sh
    content: |
        rm /home/azureuser/myapp/cat.txt >> /home/azureuser/myapp/cleanup.txt
        rm /home/azureuser/myapp/backend.txt >> /home/azureuser/myapp/cleanup.txt      
runcmd:
  - cd "/home/azureuser/myapp"
  - echo "*/15 * * * * /home/azureuser/myapp/job.sh" >> /etc/crontab
  - echo "* * * * * /home/azureuser/myapp/cleanup.sh" >> /etc/crontab